### ISSUE TITLE
Fertilized dirt is awkward in Compact Machines world type

### ISSUE THREAD

**Issue by FunnyMan3595** [Darkosto/SkyFactory4Issues#481] opened 2019-04-20 13:33 UTC
## Context
As of 4.0.1, the Compact Machines world type starts the player with two bonsai pots containing dirt trees and fertilized dirt.  While it is possible to both harvest and replace the sapling in these pots without breaking them, a clueless or careless player may end up breaking them.

For players at the start of prestige mode, once the pots are broken, the fertilized dirt becomes an "Unfamiliar Item", making it tricky to re-insert it into a bonsai pot.  If you are quick, it's possible to swap to the item and insert it before it is dropped, but it's not a smooth experience.

A better setup might be to give the player three pots and normal dirt instead,  The third pot would provide similar net speed, and also give the player an opportunity for an early upgrade by switching to either grass or dirt amber.

**Comment by skermajo** [comment] 2019-04-20 13:35
See #447

**Comment by sk2048** [comment] 2019-04-20 14:25
Duplicate of #447

**Closed by sk2048** 2019-04-20 14:25 UTC
