### ISSUE TITLE
Prestige 

### ISSUE THREAD

**Issue by albvalort** [Darkosto/SkyFactory4Issues#285] opened 2019-04-17 01:30 UTC
## Bug Report

When I press the letter "P" the prestige menu doesnt show up and crashes Minecraft

## Expected Behaviour

When pressing P, prestige menu showing off.

## Steps to Reproduce (for bugs)

1. Pressing P inside a new world

## Logs

* Client/Server Log: https://gist.github.com/albvalort/bf05bbd95d1b479cde4b44c6b935b062
* Crash Log: https://pastebin.com/FJaY4Hfz

## World Information

* Preset: StoneBlock

* Prestige: Yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed: No

## Client Information

* Modpack Version: 4.0.1
* Java Version: 8.211
* Launcher Used: Twitch
* Memory Allocated: 7G
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Crackerhead22** [comment] 2019-04-17 01:51
Just a note, make sure the Twitch Launcher is set to use the latest Java version.  Not sure if that would help or not.

**Comment by sk2048** [comment] 2019-04-17 01:54
Duplicate of #217

**Closed by sk2048** 2019-04-17 01:54 UTC
Labels: Duplicate
