### ISSUE TITLE
Unable to craft deep mob learning data models 

### ISSUE THREAD

**Issue by Shimo8** [Darkosto/SkyFactory4Issues#707] opened 2019-04-27 03:01 UTC
## Bug Report
 There's no way to craft the deep mob learning data models for almost all of the mobs. I'm aware that this issue has already been reported but not with the full format so here I am.
 You should be able to craft them(zombie with flesh etc.) normally, but it doesn't show up in JEI and doesn't work manually.

## Expected Behaviour
The models should be craftable.
 Making the deep mob learning models craftable using jei/manually.

## Possible Solution
Add the crafting recipe to JEI and make it work.

## Steps to Reproduce (for bugs)

1. try to craft a data model that is not the dragon
2. fail to do it

## Logs

* Client/Server Log: not needed
* Crash Log:again not needed 

## World Information

* Preset: normal skyfactory world.

* Prestige: no
4.0.2
* Modpack Version world created in:4.0.2

* Additional Content Installed:none

## Client Information

* Modpack Version: 4.0.2
* Java Version: I'm not sure
* Launcher Used:twitch
* Memory Allocated: 2 gigs
* Server/LAN/Single Player: singleplayer
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Lithorn** [comment] 2019-04-27 14:38
I'm able to craft them in 4.0.3, try updating and see if that helps

**Comment by CharCharthemonkey** [comment] 2019-04-28 21:14
@Lithorn umm depends on the world type but even on 4.0.3 for atleast 1 world type they arent craftable but on others they are

**Comment by sk2048** [comment] 2019-04-29 00:30
Duplicate of #520

**Closed by sk2048** 2019-04-29 00:30 UTC
