### ISSUE TITLE
Iron Ore

### ISSUE THREAD

**Issue by Adam022695** [Darkosto/SkyFactory4Issues#963] opened 2019-05-17 20:07 UTC
## Bug Report
Iron ore doesn't become molten iron in the smeltery

## Expected Behaviour
I would expect the iron ore to become molten in the smeltery

## Steps to Reproduce (for bugs)

1.Put ore in the smeltery
2.The smeltery says it cant be molten

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Normal skyfactory

* Prestige: yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.5
* Java Version:Version 8 211 (build 1.8.0_211-b12)
* Launcher Used: twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: single
* Optifine Installed: no
* Shaders Enabled: yes

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Adam022695** [comment] 2019-05-17 20:12
Update. I've tried more vinella ores and none of them can be molten in the smeltery

**Comment by sk2048** [comment] 2019-05-17 20:14
Duplicate of #381 - fixed in next release

**Closed by sk2048** 2019-05-17 20:14 UTC
