### ISSUE TITLE
create Project TrEe world just by changing name

### ISSUE THREAD

**Issue by r7787** [Darkosto/SkyFactory4Issues#513] opened 2019-04-21 04:28 UTC
## Bug Report

Able to create a Project TrEe world when it is suppose to be disabled.

## Expected Behaviour

If you go into the Project TrEe world then change the name the create new world option becomes available.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:Project TrEe

* Prestige: enabled

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by justinrusso** [comment] 2019-04-21 22:19
Duplicate of #439

**Closed by justinrusso** 2019-04-21 22:19 UTC
