### ISSUE TITLE
Crash Loop on Server 

### ISSUE THREAD

**Issue by Froggg** [Darkosto/SkyFactory4Issues#996] opened 2019-05-23 01:55 UTC
## Bug Report

Not entirely certain what the root of the issue is, I had just made something in the ME system, my friend was fighting a wither, or maybe doing mystical agriculture, then the server crashed. Went to start it up again and it crashed on startup 3 times with what appears to be the same error. Crashes as soon as it loads the world in.

## Expected Behaviour

I would expect the Crash and Restart to fix most issues, but it seems to be an issue with something in the world causing a crash. I would imagine anything buggy would just be ignored or deleted but this is crashing it instead.

## Steps to Reproduce (for bugs)

Just loading the world is enough to trigger it, again I'm not sure what caused it here so I can't really give steps to reproduce. I can detail that at the time I had running something like 128 heat generators with a bunch of lava generating setups, a half built fusion reactor, and basic crafting and refining automation for amber and materials using an ME system and Mekanism. Also had all the nuclearcraft machines required for advanced materials. Some mystical agriculture and cyclic harvesters, 2 large smelteries, Inscriber automation for AE2, Mulch automation up to blue mulch so all chemical machines required. Setting up any one of these things could cause the crash, I'm not sure which it was.

## Logs

* Client/Server Log:
[Server Log For Startup](https://gist.github.com/Froggg/db6f9ce7d9263ab03e27aaa5c2ca3655)
* Crash Log:
[Crash Report](https://pastebin.com/svGJWSyn)

## World Information

* Preset: Sky Factory 4

* Prestige: Don't know. Most of the server is default

* Modpack Version world created in: 4.03 when creating world, now running 4.05

* Additional Content Installed: N/A

## Client Information

* Modpack Version: 4.05
* Java Version: 8 Update 201
* Launcher Used: MultiMC
* Memory Allocated: 512-8192M
* Server/LAN/Single Player: Server
* Optifine Installed: Unsure, Whatever is default
* Shaders Enabled: Unsure, Whatever is default

## Server Information
* Java Version: 1.8.0_201-b09
* Operating System: Windows 10 Home Version 10.0.17134 Build 17134
* Hoster/Hosting Solution: Same PC as client, running 6600K@4.8GHz With 16GB (8 dedicated) DDR4@2133MHz
* Sponge (Non-Vanilla Forge) Server: No

**Comment by sk2048** [comment] 2019-05-23 03:11
Duplicate of #688

**Closed by sk2048** 2019-05-23 03:11 UTC
