### ISSUE TITLE
Server crash on start / Ticking tile block entity - nuclearcraft

### ISSUE THREAD

**Issue by Immow** [Darkosto/SkyFactory4Issues#742] opened 2019-04-28 18:58 UTC
## Bug Report
Server crashes on launch

## Logs
* Client/Server Log: https://gist.github.com/Immow/c59354461bed1d9907f060d6143dae27

**Comment by sk2048** [comment] 2019-04-28 19:01
Duplicate of #688

**Closed by sk2048** 2019-04-28 19:01 UTC
