### ISSUE TITLE
Mekanism dusts bug

### ISSUE THREAD

**Issue by Seriy500** [Darkosto/SkyFactory4Issues#266] opened 2019-04-16 19:01 UTC
Processing gold, iron, copper, tin, lead, silver, in mekanism machines output dust  which may be used only in nuclear craft melter.

**Comment by justinrusso** [comment] 2019-04-16 19:07
Duplicate of https://github.com/Darkosto/SkyFactory4Issues/issues/232

**Closed by justinrusso** 2019-04-16 19:07 UTC
