### ISSUE TITLE
Resource Hogs gold bacon smelting into steel

### ISSUE THREAD

**Issue by Dr-Turtle** [Darkosto/SkyFactory4Issues#632] opened 2019-04-24 22:40 UTC
## Bug Report

When putting Bacon Type: Gold from Resource Hogs into the tinker's construct smeltery, it turns into 244mb molten steel.
## Expected Behaviour

The gold bacon should turn into 244mb molten gold
## Possible Solution

change the recipe for gold bacon to molten gold instead of steel (as I assume this is the issue)

## Steps to Reproduce (for bugs)

1. Place Bacon Type: Gold into a tinker's construct smeltery (have not tested melter)

## World Information

* Preset: Sky Factory 4

* Prestige: Disabled

* Modpack Version world created in: 1.0.0

* Additional Content Installed: Laggoggles

## Client Information

* Modpack Version: 4.0.2
* Java Version: jdk1.8.0_201
* Launcher Used: Twitch
* Memory Allocated: 12gb (server)
* Server/LAN/Single Player: Server
* Optifine Installed: on client (not server)
* Shaders Enabled: no

## Server Information
* Java Version: jdk1.8.0_201
* Operating System: Windows 10 Home
* Hoster/Hosting Solution: N/A
* Sponge (Non-Vanilla Forge) Server: N/A

**Comment by sk2048** [comment] 2019-04-24 22:51
Duplicate of #451

**Closed by sk2048** 2019-04-24 22:51 UTC
