### ISSUE TITLE
Duping Items with Simple Storage

### ISSUE THREAD

**Issue by Joshua9440** [Darkosto/SkyFactory4Issues#865] opened 2019-05-06 22:01 UTC
# Bug Report
When having locked filing cabnets linked up with Simple Link Cables to a Simple Storage System, and crafting it the system does not take the items out of the cabinets.

## Expected Behaviour
The Simple Storage network doesn't take items out of a locked drawer.

## Steps to Reproduce (for bugs)

1.Set up basic Simple Storage network with Request Table, Controller, and Network Master
2.Set up a filing cabnet with resources from a tree
3.Lock it
4. Use Storage Network Cables to link to the network
5.Profit??
Video Link too: https://youtu.be/EodtAGuK6ic

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:My game is Sky Factory 4. The New game example was the floating material one.

* Prestige: On my survival go yes. On the new world no.
 
* Modpack Version world created in: Both in 4.0.5

* Additional Content Installed: None

## Client Information

* Modpack Version: Both in 4.0.5
* Java Version: 14.23.5.2831
* Launcher Used: Twitch
* Memory Allocated: 12288mb
* Server/LAN/Single Player: SinglePlayer
* Optifine Installed: no 
* Shaders Enabled: no

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Proofstar** [comment] 2019-05-07 01:38
Please try the Search Function : https://github.com/Darkosto/SkyFactory4Issues/issues/495

**Comment by Joshua9440** [comment] 2019-05-07 01:47
Oh my bad I must have searched the FTB reddit instead of this

**Comment by sk2048** [comment] 2019-05-07 03:44
Duplicate of #495

**Closed by sk2048** 2019-05-07 03:44 UTC
