### ISSUE TITLE
Recipe missing for Deep Mob Learning Simulation Chamber

### ISSUE THREAD

**Issue by Uriah-Heep** [Darkosto/SkyFactory4Issues#294] opened 2019-04-17 05:55 UTC
## Bug Report
JEI does not show any recipe for Simulation Chamber from Deep Mob Learning, recipe shows fine for Loot Fabricator and when looking for recipes that use the Soot Covered Machine Casing the Simulation Chamber does not appear.

## Expected Behaviour
Selecting the Simulation Chamber in JEI should show relevant recipe, thought at first it might be disabled but it appears as an achievement under age of power

## Possible Solution
text for both Loot Fabricator and Simulation chamber denote "acquire" rather than "craft" maybe I am just dense and have to look for the chamber in lost cities or another location 

## Steps to Reproduce (for bugs)

1. Attempt to select Simulation Chamber in JEI, no recipe displays
2. Look at recipes where the Simulation Chamber is used and try to select the simulation chamber image on the left, no recipe displays
3. Look up recipes using the Soot Covered Machine casing and Simulation Chamber is not listed,

## World Information
* Preset: Observatree

* Prestige: No

* Modpack Version world created in: 4.0.1
* Additional Content Installed: none

## Client Information

* Modpack Version: 4.0.1
* Java Version: Java 8 build 191 
* Launcher Used: Twitch
* Memory Allocated: 7842 MB
* Server/LAN/Single Player: LAN
* Optifine Installed: no
* Shaders Enabled: no

**Comment by justinrusso** [comment] 2019-04-17 16:28
Duplicate of #289

**Closed by justinrusso** 2019-04-17 16:28 UTC
