### ISSUE TITLE
Nether bug on Seven Seas world type

### ISSUE THREAD

**Issue by bradp77** [Darkosto/SkyFactory4Issues#404] opened 2019-04-19 13:45 UTC
## Bug Report

Theres an issue in the Topography.txt where the seven seas preset has the nether set to SF4.registerDimension(-1, "SF4/nether/water_nether") when it should be SF4.registerDimension(-1, "SF4/nether/nether_water").

This causes the nether to not spawn correctly leading to it being unusable
## Expected Behaviour

Nether should spawn with preset but doesn't
## Possible Solution

Change "SF4/nether/water_nether"
## Steps to Reproduce (for bugs)

1. Try enter the nether on the seven seas world type 
2.

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## World Information

* Preset: Seven Seas

* Prestige: No

* Modpack Version world created in: 4.0.1

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment] 2019-04-19 13:49
Duplicate of #348

**Closed by sk2048** 2019-04-19 13:49 UTC
