### ISSUE TITLE
Something wicked this way comes - Hostile mob spawns are "unusual"

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#29] opened 2018-10-06 18:41 UTC
Built a mob farm in the overword (Taiga M biome) and the distribution of hostile mobs is strange:
Blizz, Basalz, and Witches are common, creepers uncommon (and are glitched), and only one enderman in 4 hours. No other mobs spawned. Blizz and Basalz drop rods and snowballs, no other mobs drop anything, not even experience.

Overworld mobs are spawning frequently in the nether (Zombies, Creepers, Witches, Endermen) and have no drops. The creepers are triggered from many blocks away but are not causing any damage when they explode. Mobs are unable to damage player. No nether mobs are spawning.

Used `/kill @e[type=!Player]` in the nether and only see Zombies, Creepers, Witches, and Endermen listed in the entity killed response

Once the mobs are killed, more mobs instantly respawn.

SkyFactory4-0.0.13

**Comment by MongoTheElder** [comment] 2018-10-06 18:46
All endermen seem to be carrying a Pebble block (block ID 5516, <statues:blockpebble>)

**Comment by MongoTheElder** [comment] 2018-10-06 19:16
The blaze spawners in the nether are inactive as well

**Comment by MongoTheElder** [comment] 2018-10-06 20:13
Sooo, a Zombie Pigman showed up in the Overworld via the Nether Portal...So they can spawn.

**Comment by MongoTheElder** [comment] 2018-10-14 16:36
More info: It looks like the mobs spawning in the nether are all "Fake" mobs:
![2018-10-14_12 34 34](https://user-images.githubusercontent.com/29290246/46919450-b2bfb480-cfad-11e8-852f-391938b42a35.png)
![2018-10-14_12 34 51](https://user-images.githubusercontent.com/29290246/46919452-b5baa500-cfad-11e8-8803-69ef3b9d63c2.png)
![2018-10-14_12 35 04](https://user-images.githubusercontent.com/29290246/46919453-b81cff00-cfad-11e8-971e-bdd6900831f9.png)

**Comment by Darkosto** [comment] 2018-10-14 18:37
I'll keep looking at it, not sure what the issue is just yet. I'll tag @mrbysco to keep the mod devs from Statues in the loop.

**Comment by Darkosto** [comment] 2018-11-26 20:14
Yeah, this issue was fixed. I forgot to close this :)

**Closed by Darkosto** 2018-11-26 20:14 UTC
Labels: bug
