### ISSUE TITLE
Recipe Conflict

### ISSUE THREAD

**Issue by Wowotabernak** [Darkosto/SkyFactory4Issues#457] opened 2019-04-20 02:54 UTC
Hey y'all got a simple recipe conflict that would need solving.

When ever i try to craft the Wooden Stake from the Rustic Mod all that shows up is the Thin Wall-Wooden from the Chinese Workshop mod. 

Thanks for all the work guys and gals

**Comment by justinrusso** [comment] 2019-04-20 03:02
Duplicate of #251

**Closed by justinrusso** 2019-04-20 03:02 UTC
Labels: Duplicate
