### ISSUE TITLE
Server crashes when attaching a flux point (with a connection already selected) to Applied Energistic's (Dense or not) Energy Cell

### ISSUE THREAD

**Issue by codyback** [Darkosto/SkyFactory4Issues#1060] opened 2019-06-04 02:55 UTC
## Bug Report
Server completely crashes as soon as you connect an Applied Energistic Energy Cell to an existing Flux Network with a Flux Plug (connection is already selected in the flux plug), have repeated it with both a Dense Energy Cell and a normal Energy Cell. Have to completely restore a backup to get World up and running again.

Running a server, not client, on 4.0.5

Client does not crash, seems to just be server side.

## Expected Behaviour
Energy Cell should be connected to Flux Network, instead server completely crashes and becomes unusable until you restore a backup.

## Possible Solution
Unsure if there is anything you could do but maybe disable Flux Networks when connecting to an energy cell.

## Steps to Reproduce (for bugs)
1. Have a Flux Point in your inventory that is already attached to an existing Flux Network
2. Attach said Flux Point to an Applied Energistic's Energy Cell (Dense or otherwise)
(the Energy Cell wasn't connected to any Applied Energistic Network)

## Logs
* Client/Server Log: https://pastebin.com/xs76C14Q
* Crash Log: https://pastebin.com/3dVx4sJX

## World Information
* Preset: Default
* Prestige: No
* Modpack Version world created in: 4.0.5
* Additional Content Installed: N/A

## Client Information
* Modpack Version: 4.0.5
* Java Version: 8 Update 191
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 8 Update 191
* Operating System: Windows 10
* Hoster/Hosting Solution: Personal VPN through Hamachi
* Sponge (Non-Vanilla Forge) Server: ???

**Comment by sk2048** [comment] 2019-06-04 03:27
Duplicate of #637

**Closed by sk2048** 2019-06-04 03:27 UTC
