### ISSUE TITLE
Please add Project EX to the Modpack.

### ISSUE THREAD

**Issue by Furious1964** [Darkosto/SkyFactory4Issues#1062] opened 2019-06-04 22:04 UTC
## Mod Details
* Name: Project EX
* CurseForge Link: https://minecraft.curseforge.com/projects/project-ex

Please add this to the pack as it adds more depth and playability to the Project E mod.

**Comment by sk2048** [comment] 2019-06-04 22:16
Duplicate of #1009

**Closed by sk2048** 2019-06-04 22:16 UTC
