### ISSUE TITLE
Nuclearcraft Alloy Furnace Full Crash

### ISSUE THREAD

**Issue by Sebe47** [Darkosto/SkyFactory4Issues#836] opened 2019-05-04 20:43 UTC
## Bug Report

I used the Nuclearcraft Alloy Furnace and the game Crashed after i put in the Second Dust. Used a Recipie with i think Lithium.

Now its crashing all the time and i cant join my world. 

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/Hak81jtX

## World Information

* Preset: SkyFactory 

* Prestige: yes
 
* Modpack Version world created in: 4.0.2

* Additional Content Installed: none

## Client Information

* Modpack Version: 4.0.5
* Java Version: Java 8 Update 161
* Launcher Used: Twitch
* Memory Allocated: 6GB
* Server/LAN/Single Player: SSP
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Tonyfriends** [comment] 2019-05-04 21:03
I'm having the same problem  in 4.0.3. https://pastebin.com/0XWNqSbQ 

I've had it crash the world before but I got back in. This time I had the parabox running, which is the only change from the last crash.

**Comment by sk2048** [comment] 2019-05-04 21:04
Duplicate of #688

**Closed by sk2048** 2019-05-04 21:04 UTC

**Comment by lbsniezek** [comment] 2019-05-14 13:57
same problem in 4.0.5 cant load world .. 

https://pastebin.com/bTk2wsxq
