### ISSUE TITLE
My Game Crashed. SinglePlayer save to be exact. [SOLVED]

### ISSUE THREAD

**Issue by kaho1910** [Darkosto/SkyFactory4Issues#1034] opened 2019-05-29 10:56 UTC
It had a server tick loop problem with the main save (the very others are fine).
I'd tried to reinstall the mod pack and read some posts but nothing seems to be in my case

I logged out in the morning there was no problem but by the noon when I try to log in there was a crash

HERE ARE THE LOG FILES: https://pastebin.com/f6rkVbVh

**Comment by Kynotzib** [comment] 2019-05-29 12:42
Did you place an energy cell from AE next to an active flux point?
If so add appliedenergistics2:dense_energy_cell and appliedenergistics2:energy_cell to the flux network blacklist in it's config

**Comment by sk2048** [comment] 2019-05-29 16:22
Duplicate of #637

**Closed by sk2048** 2019-05-29 16:22 UTC
