### ISSUE TITLE
I crash when I open 

### ISSUE THREAD

**Issue by Pandalover7809** [Darkosto/SkyFactory4Issues#330] opened 2019-04-18 00:42 UTC
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:
[issue.txt](https://github.com/Darkosto/SkyFactory4Issues/files/3092036/issue.txt)

**Comment by darkhax** [comment] 2019-04-18 03:13
This issue is related to https://github.com/JarHax/Prestige/issues/6 which has already been fixed in later updates. You can manually [update Prestige](https://minecraft.curseforge.com/projects/prestige/files/2700350) to fix this issue, or wait for the next pack update.

**Comment by justinrusso** [comment] 2019-04-18 23:25
Duplicate of https://github.com/Darkosto/SkyFactory4Issues/issues/217

**Closed by justinrusso** 2019-04-18 23:25 UTC
Labels: Status: Mod Release Available, Type: Bug
