### ISSUE TITLE
Compact Machine World - Glitch Armour Impossible

### ISSUE THREAD

**Issue by KGEvans** [Darkosto/SkyFactory4Issues#790] opened 2019-05-01 04:54 UTC
## Bug Report

When starting a CompactSky preset you are unable to find an area larger than 13x13x13. In order to obtain Glitch Hearts, and by extension Glitch Armor,  you are required at least a 15x15x10 area.

## Expected Behaviour

The Achievement "Armor 404" in the Age of Enhancement tab requires a Trial Keystone. This cannot function with the limited space.

## Possible Solution

An alternate recipe for the Glitch Armour specifically for CompactSky presets. Or another way to obtain Glitch Hearts.

## Steps to Reproduce (for bugs)

1. Create a CompactSky preset world.
2. Create a Trial Keystone and look at its UI.

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## World Information

* Preset: CompactSky

* Prestige: N/A, but yes.

* Modpack Version world created in: 4.0.2

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.3
* Java Version: 
* Launcher Used: TwitchApp
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by heke85** [comment] 2019-05-01 05:39
Duplicate of #570

**Closed** 2019-05-01 06:20 UTC
Labels: Duplicate
