### ISSUE TITLE
Server Crash Ticking block entity

### ISSUE THREAD

**Issue by WujcioKarol** [Darkosto/SkyFactory4Issues#953] opened 2019-05-15 17:18 UTC
## Bug Report
crasing server

## Steps to Reproduce (for bugs)

1.start server
2.crash

## Logs

This is only ive got cause i use aternos without acces to FTP

940 | [18:45:16] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
-- | --
4941 | net.minecraft.util.ReportedException: Ticking block entity
4942 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
4943 | at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
4944 | at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
4945 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
4946 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
4947 | Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
4948 | at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_202]
4949 | at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_202]
4950 | at nc.recipe.ingredient.ItemArrayIngredient.getMaxStackSize(ItemArrayIngredient.java:53) ~[ItemArrayIngredient.class:?]
4951 | at nc.tile.processor.TileItemProcessor.produceProducts(TileItemProcessor.java:263) ~[TileItemProcessor.class:?]
4952 | at nc.tile.processor.TileItemProcessor.finishProcess(TileItemProcessor.java:249) ~[TileItemProcessor.class:?]
4953 | at nc.tile.processor.TileItemProcessor.process(TileItemProcessor.java:244) ~[TileItemProcessor.class:?]
4954 | at nc.tile.processor.TileItemProcessor.updateProcessor(TileItemProcessor.java:113) ~[TileItemProcessor.class:?]
4955 | at nc.tile.processor.TileItemProcessor.func_73660_a(TileItemProcessor.java:105) ~[TileItemProcessor.class:?]
4956 | at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
4957 | at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
4958 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
4959 | ... 4 more

## World Information
* Preset: dirt 

* Prestige: 
no
* Modpack Version world created in:
4.0.5
* Additional Content Installed:
no

## Client Information

* Modpack Version:4.0.5
* Java Version:java 8 update 201
* Launcher Used:twitch
* Memory Allocated:2.5GB on server
* Server/LAN/Single Player:server
* Optifine Installed:no
* Shaders Enabled:no

## Server Information
* Java Version:1.8
* Operating System:idk

**Comment by sk2048** [comment] 2019-05-15 17:19
Duplicate of #688

**Closed by sk2048** 2019-05-15 17:19 UTC
