### ISSUE TITLE
visual bug with chest builder

### ISSUE THREAD

**Issue by MDviper** [Darkosto/SkyFactory4Issues#561] opened 2019-04-22 12:58 UTC
***** not sure how to add a log for this *****

## Bug Report
When in the inventory of the biggest chest builder chest when modifying the inventory by adding, removing the items in the chest disappear. not sure if its a mod issue or something else 

## Steps to Reproduce (for bugs)

1. build the 24 row 12 column chest builder chest. (color doesnt matter)
2. Place chest
3. place different multiple items into chest
4. close chest and reopen (items will appear)
5. place or remove one item as before or different item or rearrange items

## World Information

* Preset: lavabox world

* Prestige: no
 
* Modpack Version world created in: 4.0.0 - has been updated to 4.0.2

* Additional Content Installed: none

## Client Information

* Modpack Version: 4.0.2
* Java Version: V8 update 211
* Launcher Used: twitch
* Memory Allocated: 8192 MB
* Server/LAN/Single Player: single
* Optifine Installed: no
* Shaders Enabled: no

**Comment by sk2048** [comment] 2019-04-22 12:59
Duplicate of #449 

You can find a solution there.

**Closed by sk2048** 2019-04-22 12:59 UTC
