### ISSUE TITLE
Thermal Evaporation Plant multi-block makes a crash.

### ISSUE THREAD

**Issue by bontavi** [Darkosto/SkyFactory4Issues#425] opened 2019-04-19 18:53 UTC
## Bug Report
Hey, I tried to form a multi-block to create Thermal Evaporation Plant and it crashed server. I tested it on a single player world and after some time it becomes unresponsive.

## Steps to Reproduce (for bugs)
1. Craft Thermal Evaporation Blocks, Thermal Evaporation Valve and Thermal Evaporation Controller from mekanism.
2. Try to form a multi-block for Thermal Evaporation plant. - https://wiki.aidancbrady.com/wiki/Thermal_Evaporation_Plant

## Logs
* Client/Server Log:
* Crash Log: https://pastebin.com/Frfhq3kc

## Client Information
* Modpack Version: 4.0.1
* Java Version: 1.8.0.51 ( 64bit )
* Launcher Used: Twitch
* Memory Allocated: 8192
* Server/LAN/Single Player: SP/ MP both effected

## Server Information
* Hoster/Hosting Solution: Nodecraft

**Comment by sk2048** [comment] 2019-04-19 18:54
Duplicate of #370

**Closed by sk2048** 2019-04-19 18:54 UTC
