### ISSUE TITLE
Sulfuric Acid in Chemical Reactor Causing Crash

### ISSUE THREAD

**Issue by kugamer** [Darkosto/SkyFactory4Issues#739] opened 2019-04-28 15:17 UTC
## Bug Report

I am trying to make calcium sulfate (I think that is what it is called). I am piping liquid sulfur trioxide into a chemical reactor with water in it. As soon as the sulfur trioxide hits the machine the server crashes. 

## Expected Behaviour

Combining water and sulfur trioxide  in a chemical reactor should combine into sulfuric acid. 

## Steps to Reproduce (for bugs)

1. I cannot produce in a single player world
2.

## Logs

* Client/Server Log:
* Crash Log:https://pastebin.com/WwevKxKf

## World Information

* Preset: skiilands

* Prestige: yes

* Modpack Version world created in: it was created in 4.0.1, we are running .3

* Additional Content Installed:

## Client Information

* Modpack Version:4.0.3
* Java Version:1.8.0.51
* Launcher Used:Twitch
* Memory Allocated:8gb
* Server/LAN/Single Player:Server
* Optifine Installed:no
* Shaders Enabled:no

## Server Information
* Java Version: not sure where I find this, I have a server from Beastnode on a multimc platform
* Operating System: Windows
* Hoster/Hosting Solution:Beastnode
* Sponge (Non-Vanilla Forge) Server: Not sure what this is

**Comment by sk2048** [comment] 2019-04-28 16:43
There is presently an issue with all nuclearcraft recipes. The ingredients must go into the correct slot as JEI indicates or the game will crash. This is being worked on.

In the case of Sulphuric Acid, the Sulphur Trioxide must be piped into the machine before the water.

Duplicate of #688

**Closed by sk2048** 2019-04-28 16:43 UTC
