### ISSUE TITLE
Mekanism Tin dust can be created and used, but does not show in JEI

### ISSUE THREAD

**Issue by Dr-Turtle** [Darkosto/SkyFactory4Issues#232] opened 2019-04-16 03:17 UTC
Mekanism Tin dust can be easily created with tin amber and a grindstone. It is not visible in JEI unless looking at recipes that Dirty Tin Dust is used in. This tin dust is not useful for quite some time.

**Comment by Nazta** [comment] 2019-04-16 08:31
It seems to be a an oversight, in that the horsepower grindstone makes the mekanism dust that is hidden from JEI and only works in mekanism machines. 

But the astral grindstone makes mekanism dust, which you can melt in a vanilla furnce.

**Comment by John2143** [comment] 2019-04-17 09:15
This also affects all Mekanism processes, not just a grindstone. Enriching any dirty ore dust produces Mekanism dusts' which cannot be used.

**Comment by MaccaPakka** [comment] 2019-04-17 20:27
Is this intended behavior? I've just setup Mechanism x3 processing and since it created Iron Dust (Mekanism) it cannot be smelted down into ingots

**Comment by Dr-Turtle** [comment] 2019-04-18 15:56
> Is this intended behavior? I've just setup Mechanism x3 processing and since it created Iron Dust (Mekanism) it cannot be smelted down into ingots

for now, you can use a nuclearcraft melter to get molten iron which can be put into a smeltery or ingot former

**Comment by MaccaPakka** [comment] 2019-04-18 19:04
"for now" leads me to believe it is in fact a bug and need the bug flag for fixing here in Github?

**Comment by sk2048** [comment] 2019-04-18 19:17
This issue has the bug label?

**Comment by justinrusso** [comment] 2019-04-19 00:47
@MaccaPakka dirty dust is a different issue but will be resolved in 4.0.2. Also, yes, both are bugs.

**Closed** 2019-05-30 01:33 UTC
Labels: Category: Unification, Type: Bug
