### ISSUE TITLE
Two Advancements for going to Lost City Dimension

### ISSUE THREAD

**Issue by Crackerhead22** [Darkosto/SkyFactory4Issues#584] opened 2019-04-22 23:39 UTC
## Bug Report
When entering the Lost City Dimension, I gain both Lost City advancements.  The one from using Lost Cities as starting World, as well as the other one.

![lostcity](https://user-images.githubusercontent.com/452429/56540303-50380a00-6536-11e9-9537-3fb8db6d7318.png)

## Expected Behaviour
Gaining only one Lost City advancement.

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
Enter Lost City.

## Logs

* Client/Server Log: https://pastebin.com/mp2j7Y4Y (I think I did this right)
* Crash Log: N/A

## World Information

* Preset: Several

* Prestige:  Both

* Modpack Version world created in: 4.0.2

* Additional Content Installed: N/A

## Client Information

* Modpack Version: 4.0.2
* Java Version: 211
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Crackerhead22** [comment] 2019-04-22 23:41
P.S. - I blame FirstNecron.  Kappa

**Comment by sk2048** [comment] 2019-04-22 23:48
Duplicate of #466 
(Already fixed)

**Closed by sk2048** 2019-04-22 23:48 UTC
