### ISSUE TITLE
Unable to acquire Nap Time advancement in Compact Sky world

### ISSUE THREAD

**Issue by IsaacWorkman** [Darkosto/SkyFactory4Issues#338] opened 2019-04-18 02:42 UTC
## Bug Report
Current Behaviour: When trying to sleep within a Compact Machine block, you cannot sleep and instead it just resets your spawn point for if you die. Happens regardless of time. The main downside to this is that it restricts a player's ability to obtain the "Nap Time" advancement in "compact sky" map types.

## Expected Behaviour
Either:
Changing spawn point within a Compact Machine should grant the Nap Time achievement.
OR
Sleeping should be possible within a compact machine.

## World Information
* Preset: CompactSky
* Prestige: Yes
* Modpack Version world created in: 4.01
* Additional Content Installed: None

## Client Information
* Modpack Version: 4.01
* Java Version: 1.8.0.51, 64 bit
* Launcher Used: Twitch
* Memory Allocated: 8192 MB
* Server/LAN/Single Player: Single player
* Optifine Installed: i don't think so?
* Shaders Enabled: no

**Comment by sk2048** [comment] 2019-04-18 05:14
Duplicate of #271

**Closed by sk2048** 2019-04-18 05:14 UTC
Labels: Type: Bug
