### ISSUE TITLE
Recipe Conflict: Wooden Stake inaccessible, instead producing Thin Wall-wooden

### ISSUE THREAD

**Issue by Jagrabbit** [Darkosto/SkyFactory4Issues#299] opened 2019-04-17 10:42 UTC
## Bug Report
Rustic `Wooden Stake` recipe cannot be crafted because it instead produces ChineseWorkshop `Thin-Wall`.  Recipe Conflict

## Expected Behaviour
Use Crafting Table with 3 vertical planks recipe produces Rustic `Wooden Stake`

## Possible Solution
Remove Thin Wall-Wooden recipe for 3 wooden planks vertical.  Instead provide access to thin Wall variants via 3 rammed earth vertical and the toggle RControl selection wheel.

## Steps to Reproduce (for bugs)

1. Use Crafting Bench
2. Place 3 planks in vertical pattern as JEI details the recipe for Wooden Stake as being.
3. Receive Thin-Wall Wooden as result preview shows.

## Client Information

* Modpack Version: 4.0.1

**Comment by sk2048** [comment] 2019-04-17 10:52
Duplicate of #251

**Closed by sk2048** 2019-04-17 10:52 UTC

**Comment by TheKellith** [comment] 2019-04-24 15:22
Other possible crafting alternates for thin wooden wall could be two vertical lines of wooden plank slabs (same resource cost, just 1 extra step), or setting both to a shaped craft in different columns.
