### ISSUE TITLE
Compact Chests sorting/update visual glitch (empty) after Update 4.0.2

### ISSUE THREAD

**Issue by Possemaster** [Darkosto/SkyFactory4Issues#468] opened 2019-04-20 07:26 UTC
Compact Chests updates visually glitch the content invisible.
So sorting with Middle Mouse Click or Compact Chests that have items piped into it will apear empty, but if you click a spot the item apears. This happened for everyone aftre updating to 4.0.2

Regular Minecraft Chests do not have this issue.

![Chest before sorting](https://user-images.githubusercontent.com/7541145/56454245-1e644f00-634e-11e9-87e1-2aa4cdc92cac.jpg)
![Chest after sorting](https://user-images.githubusercontent.com/7541145/56454246-1e644f00-634e-11e9-809e-ca71536a1a73.jpg)

**Comment by Petrel63** [comment] 2019-04-20 07:36
I have the above issue but thought I would just add that updating the mod ComPatchedStorage to the newest version (i.e. ComPatchedStorage-1.12.2-1.5.1.jar) resolved the issue.

Hope this helps, thanks for all the work you do.

**Comment by NyxCode** [comment] 2019-04-20 08:59
Same issue here

**Comment by RobbeSchepens** [comment] 2019-04-20 09:55
Note that it's **not** just sorting from the middle mouse button, it seems to be any action in the chest such as left clicking on an empty spot or attempting to get a stack out by shift+clicking on it. 

I have updated ComPatchedStorage from 1.4.0 to 1.5.1 as Petrel63 suggested, and it does resolve the issues I had.

**Comment by b0bst3r** [comment] 2019-04-20 14:16
As someone who has a base full of these chests this bug makes the pack unplayable, as Robbe above said it's not just sorting, trying to remove any item from the chest causes contents to visually disappear.

**Comment by blacksythe** [comment] 2019-04-20 19:03
May be related but I can no longer craft these chests in the chest workbench.

**Comment by Shadows-of-Fire** [comment] 2019-04-20 20:58
The chest workbench is broken on dedicated servers.  That has also been resolved as of ComPatched 1.5.1

**Comment by Layarion** [comment] 2019-04-20 21:36
Please put 1.5.1 in a 4.0.2 patch? i don't want to manually track things like this with each server i have.

**Comment by justinrusso** [comment] 2019-04-21 22:15
Duplicate of #449

**Closed by justinrusso** 2019-04-21 22:15 UTC
Labels: Category: Mod, Status: Mod Release Available, Type: Bug
