### ISSUE TITLE
Unforgiving Void Multiplayer

### ISSUE THREAD

**Issue by Hail4Gaming** [Darkosto/SkyFactory4Issues#572] opened 2019-04-22 19:39 UTC
Forgiving Void is not working for myself on a server I am hosting. On the server are two other people and they are respawning at the top correctly. I have 3 added mods, Player Skin Mob, FTBUtils, and Content Creator Integration. I was originally not going to post this, as I thought CCI was the problem because it was the only difference between us, however in Singleplayer I am successfully falling and respawning at world height. However, in Multiplayer it still does not work for some reason.

## Bug Report
Falling into void drains my health to 0, spawning tombstone on my island and respawning me there. It works correctly for all other players on the server, however-only I have the issue.

## Expected Behaviour
Falling into the void, in singleplayer (and everyone else on the server) respawns me at world height and I fall onto my island correctly.

## Steps to Reproduce (for bugs)
1. I log into my server
2. I fall off island
3. I die in void.

## Things done to check for cause
I deop myself to see if op is the issue. I removed claims with FTBU (another player has their island claimed as well and has no issues). None of these solutions worked. Attempted in Singleplayer and it worked correctly.

## Logs
No Crash, No Log

## World Information

* Preset: SF4 Classic

* Prestige: DISABLED 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.2
* Java Version: 1.8.0_51
* Launcher Used: Twitch
* Memory Allocated: 8192MB Client, 10240MB Server
* Server/LAN/Single Player: Server (works in Singleplayer properly)
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: Unknown
* Operating System: Linux? Unknown
* Hoster/Hosting Solution: MelonCube
* Sponge (Non-Vanilla Forge) Server: No

**Comment by sk2048** [comment] 2019-04-22 21:47
Duplicate of #254

**Comment by Hail4Gaming** [comment] 2019-04-22 22:02
But it isnt a duplicate? I dont get stuck at y300 and it was with version 4.0.2? genuinely curious. I looked around and saw that one but didnt feel it was the same.

**Comment by sk2048** [comment] 2019-04-22 22:16
You are correct, there have been so many issue reports and on skim reading I picked up the words "server" and "respawning at the top"

Can you run `/gamestages info` please?

**Comment by Hail4Gaming** [comment] 2019-04-23 19:51
Upon attempting that command it states "unknown command"

**Comment by sk2048** [comment] 2019-04-23 20:07
Apologies, I meant `/gamestage info`

**Comment by Hail4Gaming** [comment] 2019-04-23 20:23
![OiRqZnw](https://user-images.githubusercontent.com/11011640/56613212-29d0a800-65e4-11e9-8fbd-f1568d8f8cde.png)
This is what I get when I do it. Sorry, I should have tried without the s as well =/

**Comment by sk2048** [comment] 2019-04-23 21:35
Somehow you're missing `forgiving_void`

Do `/gamestage add @p forgiving_void` and try jumping :)

**Comment by sk2048** [comment] 2019-04-23 21:36
You also don't seem to have `non_pacifist`, so add that too or you'll be missing some recipes.

**Comment by Hail4Gaming** [comment] 2019-04-23 21:57
I added both, just as you said. -- forgiving_void now works thanks to that, and you said to add non_pacifist, so I did, thanks :)

**Closed** 2019-04-24 21:19 UTC
