### ISSUE TITLE
Potion Fabricator Causing Crash on Tick

### ISSUE THREAD

**Issue by Froggg** [Darkosto/SkyFactory4Issues#1016] opened 2019-05-25 14:08 UTC
## Bug Report

Server shuts down on load due to a ticking block entity. The Industrial foregoing potion enervator (fabricator? goes by enervator in code but player working on it says thats what it was).  No idea what was going it but it caused a crash.

## Expected Behaviour

Expected behavior is for the block to function as intended, and reject any incompatible inputs

## Possible Solution

Have Block reject incompatible inputs or fix broken but "functional" inputs

## Steps to Reproduce (for bugs)

Not entirely sure what was happening with it but put something in the potion enervator. probably very similar to 688.

## Logs

* Client/Server Log:
[Server Log For Startup](https://gist.github.com/Froggg/efa9a5e583f3f73f61ba8949b9d52778)
* Crash Log:
[Crash Report](https://gist.github.com/Froggg/9113ff6f509a2666e3704fa34ea2202f)

## World Information

* Preset: Sky Factory 4

* Prestige: Don't know. Most of the server is default

* Modpack Version world created in: 4.03 when creating world, now running 4.05

* Additional Content Installed: N/A

## Client Information

* Modpack Version: 4.05
* Java Version: 8 Update 201
* Launcher Used: MultiMC
* Memory Allocated: 512-8192M
* Server/LAN/Single Player: Server
* Optifine Installed: Unsure, Whatever is default
* Shaders Enabled: Unsure, Whatever is default

## Server Information
* Java Version: 1.8.0_201-b09
* Operating System: Windows 10 Home Version 10.0.17134 Build 17134
* Hoster/Hosting Solution: Same PC as client, running 6600K@4.8GHz With 16GB (8 dedicated) DDR4@2133MHz
* Sponge (Non-Vanilla Forge) Server: No

**Comment by sk2048** [comment] 2019-05-26 08:19
Duplicate of #565

**Closed by sk2048** 2019-05-26 08:19 UTC
