### ISSUE TITLE
More Buckets - Buckets of water, CANNOT be used on Cauldrons Full of Lava

### ISSUE THREAD

**Issue by ArkavianX** [Darkosto/SkyFactory4Issues#729] opened 2019-04-28 01:11 UTC
A bit more context, I've made several of the More Buckets because of their fluid capacity, but was immediately dismayed when I tried to make obsidian. 

It didn't matter which More Bucket I used, none of them worked. 

Tested in 4.0.2 & 4.0.3

**Comment by sk2048** [comment] 2019-04-28 16:44
Duplicate of #321

**Closed by sk2048** 2019-04-28 16:44 UTC
Labels: Category: Mod
