### ISSUE TITLE
Crash upon load

### ISSUE THREAD

**Issue by Jdreioe** [Darkosto/SkyFactory4Issues#835] opened 2019-05-04 19:33 UTC
## Bug Report
´
I was in my Stonefactory world base, when suddenly my game crashes. Upon world launch again, it crashes again.

## Expected Behaviour

To load the world

## Steps to Reproduce (for bugs)

1. Load world
2. Ceash

## Logs

* Client/Server Log: https://gist.github.com/Jdreioe/eeb65c259f81a33d50980f2ca8edb86c
* Crash Log: https://gist.github.com/Jdreioe/3a77f69810e82e7aab9db96cd3c7f852

## World Information

* Preset: StoneFactory

* Prestige: Yes

* Modpack Version world created in:
4.0.3

* Additional Content Installed:
None
## Client Information

* Modpack Version: 4.0.5
* Java Version: 8 update 171
* Launcher Used: Twitch, native
* Memory Allocated: 9 Gb
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No
* Resource pack: Unity

**Comment by sk2048** [comment] 2019-05-04 21:07
Duplicate of #688

**Closed by sk2048** 2019-05-04 21:07 UTC
Labels: Category: Mod, Type: Crash
