### ISSUE TITLE
Cobalt and Ardite cant smelt in smeltery

### ISSUE THREAD

**Issue by CaptainQuirkz** [Darkosto/SkyFactory4Issues#482] opened 2019-04-20 13:41 UTC
## Bug Report

Cobalt and Ardite ores do not smelt in Tinkers Smeltery, only the melter.
## Expected Behaviour

Cobalt and Ardite ores can smelt in Tinkers Smeltery
## Steps to Reproduce (for bugs)

1.place Cobalt or Ardite in tinkers smeltery (not melter)

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Pacifist

* Prestige: No

* Modpack Version world created in: 4.0.1

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.2
* Java Version: 8
* Launcher Used: ATLauncher
* Memory Allocated: 4GB
* Server/LAN/Single Player: single player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by DingoX3** [comment] 2019-04-20 18:35
Try processing them into an ingot first. I used an Enrichment Chamber-then smelted in a furnace-placed into smeltery.

**Comment by rbridge** [comment] 2019-04-22 21:02
Following Dingo's comment you can crush the ore and smelt in to ingot then smelt to the molten form.

Do we know if ore melting is intentionally disabled in the smeltery for any particular reason?

**Comment by justinrusso** [comment] 2019-05-02 12:36
Duplicate of #381

**Closed by justinrusso** 2019-05-02 12:36 UTC
