### ISSUE TITLE
Mulch Unlock Order is Off

### ISSUE THREAD

**Issue by xLyfa** [Darkosto/SkyFactory4Issues#287] opened 2019-04-17 02:07 UTC
The mulch unlock progression in the prestige window is out of order. The prestige costs go from  1 -> 2 -> 4 -> 6 -> 12 -> 10 -> 14 -> 8, and the bonuses the mulch gives doesn't make sense in the current unlock order.

Playing on the Classic Sky Factory 4 map with prestige enabled, pack version 4.0.1.

![image](https://user-images.githubusercontent.com/44540647/56255755-006bc580-6094-11e9-9490-20261a0b2708.png)

**Comment by sk2048** [comment] 2019-04-17 02:08
Duplicate of #165

**Closed by sk2048** 2019-04-17 02:08 UTC
