### ISSUE TITLE
Wooden Stakes conflict with Thin Wall-Wooden

### ISSUE THREAD

**Issue by llhilton** [Darkosto/SkyFactory4Issues#353] opened 2019-04-18 13:53 UTC
## Bug Report
Currently, you cannot craft the wooden stakes from rustic. The recipe is in conflict with the Chinese Workshop recipe for Thin Wall-wooden. 

## Expected Behaviour
It would be expected to be able to make both. Perhaps the stakes could use logs instead of planks? So many logs. Need things to do with logs!

**Comment by sk2048** [comment] 2019-04-18 13:58
Duplicate of #251

**Closed by sk2048** 2019-04-18 13:58 UTC
