### ISSUE TITLE
Add Patchouli

### ISSUE THREAD

**Issue by 016Nojr** [Darkosto/SkyFactory4Issues#795] opened 2019-05-01 17:55 UTC
## Context
Deep Mob Learning requires Patchouli to read its guide in game. I am 100% aware it's an already created issue (#563), but the mod wasnt added in the latest update (6 days ago) and the issue was created and tagged 9 days ago without any response after that.

## Mod Details
* Name: Patchouli
* CurseForge Link: [Link](https://minecraft.curseforge.com/projects/patchouli?gameCategorySlug=mc-mods&projectID=306770)

**Comment by sk2048** [comment] 2019-05-01 17:56
Duplicate of #563

**Closed by sk2048** 2019-05-01 17:56 UTC
