### ISSUE TITLE
Animal Seeds Dupe

### ISSUE THREAD

**Issue by AnimatorOfSouls** [Darkosto/SkyFactory4Issues#498] opened 2019-04-20 20:42 UTC
## Bug Report
Duping animal seeds by using tiny progressions watering can and quickly flicking on then off of the seed while holding right click. Tested it with chickens + cows before running out of corn.

## Expected Behaviour
The seed should just disappear after the mob is spawned, but in this case it gives you a new seed.

## Steps to Reproduce (for bugs)
Video shows the glitch. Skip to 1:25 to see what it looks like when I'm not flicking on and off.
https://www.youtube.com/watch?v=jdiQvDrtFRk

## World Information

* Preset: Default Skyfactory

* Prestige: Yes

* Modpack Version world created in: 4.0.2

* Additional Content Installed: FTBUtils and FTBLib

## Client Information

* Modpack Version: 4.0.2
* Java Version: V8 211
* Launcher Used: Twitch
* Memory Allocated: 6GB
* Server/LAN/Single Player: Server
* Optifine Installed: Nope
* Shaders Enabled: Nope

## Server Information
2 x Intel Xeon CPU 5690x @3.5GHz 6 cores, 12 threads, 136GB ram, 3x SSD 250gb

**Comment by sk2048** [comment] 2019-04-20 20:54
Duplicate of #336 #377

**Closed by sk2048** 2019-04-20 20:54 UTC
