### ISSUE TITLE
Making An Advanced Solar Panel

### ISSUE THREAD

**Issue by 4e5ntre5h38y** [Darkosto/SkyFactory4Issues#514] opened 2019-04-21 06:10 UTC
## Bug Report
 whenever make a advanced solar panel or putting 4 solar generators from mekanism into a tinkers crafting bench connected to a chest the game crashes.
not crash

## Expected Behaviour
 game crashes whenever i have tried to craft using the Jei to put in or doing to manually 

## Steps to Reproduce (for bugs)

1.make 4 solar generators 
2. put all four into a tinkers crafting station connected to a chest
3. or use the jei to put all 4 in to try and make an advanced solar generator

## Logs
 

* Client/Server Log: https://pastebin.com/8BEMYfxw
* Crash Log :https://pastebin.com/8BEMYfxw

## World Information

* Preset: default 

* Prestige: no
 
* Modpack Version world created in: 4.0.2

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.2
* Java Version:
* Launcher Used: twitch
* Memory Allocated: 6 gb
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: ni

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment] 2019-04-21 12:41
Duplicate of #405

**Closed by sk2048** 2019-04-21 12:41 UTC
