### ISSUE TITLE
Chicken Feed recipe missing

### ISSUE THREAD

**Issue by boballama** [Darkosto/SkyFactory4Issues#854] opened 2019-05-06 02:25 UTC
I completed a Prestige point while still on the 4.0.3 version and chose to spend my point on the mob grinding Utilities.  I updated to 4.0.5 soon after.  I am now trying to satisfy the newly added advancement regarding Chicken Feed.  But there is no recipe for Chicken Feed.  There is a note that implies a mob grinding Utils prerequisite.  But that has been met.

There has been no crash, therefore no crash logs.

I am running no other mods and using the Twitch Launcher.

## World Information

Default, start on top of a single tree on a single block of dirt.

* Preset:

Yes.

* Prestige: 

Probably 4.0.2.

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

I'm not sure how much any of this other information is worth.  It is not a problem with my system but rather a missing recipe or an inaccurate assessment of prestige points enabling the mob grinding utilities that appears to be a prerequisite.

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

No server involved, playing single player.

**Comment by sk2048** [comment] 2019-05-06 02:46
Duplicate of #511

**Comment by sk2048** [comment] 2019-05-06 02:47
(Recipe exists, read the advancement description - mod issue prevents it from showing correctly in JEI)

**Closed by sk2048** 2019-05-06 02:46 UTC

**Comment by WhisperFire26** [comment] 2019-05-10 18:29
How do you get the recipe to properly show in JEI? Is there a work around?

**Comment by sk2048** [comment] 2019-05-10 18:33
No workaround as such, the recipe class needs a JEI plugin I believe.
