### ISSUE TITLE
ComPatchedStorage chest builder doesnt work on server

### ISSUE THREAD

**Issue by HighCrit** [Darkosto/SkyFactory4Issues#538] opened 2019-04-21 21:59 UTC
## Bug Report
ComPatchedStorage's chestbuilder does not give a chest when building one on a server.

## Expected Behaviour
Receiving the desired chest.

## Steps to Reproduce (for bugs)
1. Place chestbuilder
2. Provide required materials
3. Press build
4. TING!
5. Nothing

## Logs

* Client/Server Log:
* Crash Log:

## World Information
All default settings from server.properties are used

## Client Information

* Modpack Version:
* Java Version: 8 v211
* Launcher Used: Twitch
* Memory Allocated: 4G
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 8 v211
* Operating System: Windows 10 Home
* Hoster/Hosting Solution: Home
* Sponge (Non-Vanilla Forge) Server: Forge

**Comment by ArcticHumboldt** [comment] 2019-04-21 22:03
Thanks for reporting this - I get the same problem.

**Comment by justinrusso** [comment] 2019-04-21 22:18
Duplicate of #436

**Closed by justinrusso** 2019-04-21 22:18 UTC

**Comment by ArcticHumboldt** [comment] 2019-04-21 22:31
I actually tested wrong - the fix in 436 does not work on the server, only client-side. ComPatchedStorage 1.5.1 is on both the server and my client, but the issue persists on the server.
