### ISSUE TITLE
Metallurgic Infuser Dump Issue

### ISSUE THREAD

**Issue by NYfan0122** [Darkosto/SkyFactory4Issues#728] opened 2019-04-28 00:59 UTC
[00:51:25] [Server thread/ERROR] [Mekanism]: Tried to increase infusion storage with an incompatible type
java.lang.Exception: null
        at mekanism.common.InfuseStorage.increase(InfuseStorage.java:58) [InfuseStorage.class:?]
        at mekanism.common.tile.TileEntityMetallurgicInfuser.onUpdate(TileEntityMetallurgicInfuser.java:94) [TileEntityMetallurgicInfuser.class:?]
        at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:89) [TileEntityBasicBlock.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1835) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

Whenever you add materials after it has been dumped, it gets dumped too.

**Comment by justinrusso** [comment] 2019-04-28 13:47
Duplicate of #710

**Closed by justinrusso** 2019-04-28 13:47 UTC
