### ISSUE TITLE
Respec Prestige Points Broken

### ISSUE THREAD

**Issue by ScorchSter** [Darkosto/SkyFactory4Issues#809] opened 2019-05-02 14:31 UTC
## Bug Report
  Respeccing after gaining a prestige point

## Expected Behaviour
 Should have gotten all of my prestige points back, instead received 4 points back.

## World Information
Skiiiilands
* Preset:

* Prestige: Yes

* Modpack Version world created in: 4.0.4

## Client Information

* Modpack Version: 4.0.4
* Java Version: 1.8.0 161
* Launcher Used: twitch
* Memory Allocated: 6 gb
* Server/LAN/Single Player: single
* Optifine Installed: no
* Shaders Enabled: no

**Comment by sk2048** [comment] 2019-05-02 14:35
As far as I can tell, this is a duplicate of #551

**Closed by sk2048** 2019-05-02 14:35 UTC
