### ISSUE TITLE
Potion brewer

### ISSUE THREAD

**Issue by SubzenRei** [Darkosto/SkyFactory4Issues#791] opened 2019-05-01 09:39 UTC
## Bug Report
I was using 'potion brewer' from industrial foregoing and suddenly my game freeze. The game won't close so I force quit it and the menu say it was a crash. I open the game again, everything was fine except my save because the game won't let me get into the server(stuck at loading screen).

I tried potion brewer in another server and same thing happens.

## Steps to Reproduce 
 
1. Right click auto-brewer with water bottle in hand
2. The game freeze and crash

## Logs
* Crash Log: https://pastebin.com/z7z6Zkzh

## World Information
* Prestige: No
* Modpack Version world created in: 4.0.3

## Client Information

* Java Version: 8.0
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sk2048** [comment] 2019-05-01 09:56
Duplicate of #565

**Closed by sk2048** 2019-05-01 09:56 UTC
Labels: Duplicate
