### ISSUE TITLE
Squeezer + Cobble = Crash

### ISSUE THREAD

**Issue by Drooski** [Darkosto/SkyFactory4Issues#373] opened 2019-04-18 22:23 UTC
## Bug Report
This is a bug report

## Expected Behaviour
According to JEI, you should be able to make gravel by placing cobble into a squeezer and jumping on it. However, doing this causes the game to crash.

## Steps to Reproduce (for bugs)

1. Place Cobblestone into Squeezer
2. Jump

## Logs

* Client/Server Log:
* Crash Log:
---- Minecraft Crash Report ----

Attached as text file

## World Information

* Preset: SkyIiiiislands

* Prestige: Yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed: Refined Storage

## Client Information

* Modpack Version: 4.0.1
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

[crash-2019-04-18_15.14.27-server.txt](https://github.com/Darkosto/SkyFactory4Issues/files/3096343/crash-2019-04-18_15.14.27-server.txt)

**Comment by sk2048** [comment] 2019-04-18 22:25
Is your squeezer right next to a compact storage crate? It's trying to push the output into that and crashing.

Duplicate of #334, hopefully fixed in 4.0.2

**Closed by sk2048** 2019-04-18 22:25 UTC

**Comment by Drooski** [comment] 2019-04-18 22:27
No compact storage, but it WAS next to a chest builder. Removed that and problem is resolved.
