### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by rossmontgo** [Darkosto/SkyFactory4Issues#936] opened 2019-05-12 22:37 UTC
I was the only one on the server at the time. I was making Tough Alloy from FerroBoron Ingots and Lithium dust in the Alloy Smelter. I shift+clicked a stack of each and the server crashed. I've attached the crash report.
[crash-2019-05-12_15.29.54-server.txt](https://github.com/Darkosto/SkyFactory4Issues/files/3170633/crash-2019-05-12_15.29.54-server.txt)

**Comment by DeciTM** [comment] 2019-05-13 00:28
> Please follow the templates, any issue which fails to provide the requested information will be closed.

You removed the form. That's there to ensure you provide the developers with all the information they need to address your issue.

**Comment by sk2048** [comment] 2019-05-13 07:46
Probably a duplicate of #688

**Closed by sk2048** 2019-05-13 07:46 UTC
Labels: Duplicate
