### ISSUE TITLE
Simple storage cable induced crash

### ISSUE THREAD

**Issue by GeneralK** [Darkosto/SkyFactory4Issues#924] opened 2019-05-11 19:17 UTC
## Bug Report
Right clicking on the simple storage import cable with a cresent hammer (wrench) crashes it.

## Expected Behaviour
Rotates the simple storage import cable's direction to desired block/inventory. 

## Steps to Reproduce (for bugs)
1. Acquire cresent hammer
2. Right click on a storage import cable from Simple Storage Networks

## Logs
* Client/Server Log:
* Crash Log: https://pastebin.com/HkjJeEwS

## World Information
* Preset: Compact 3x3x3
* Prestige:  Yes

* Modpack Version world created in: 1.12.2
* Additional Content Installed: None

## Client Information
* Modpack Version: 4.0.5
* Java Version: Unknown
* Launcher Used: Twitch
* Memory Allocated: 3Gb
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sk2048** [comment] 2019-05-11 20:34
Duplicate of #508

**Closed by sk2048** 2019-05-11 20:34 UTC
